name: build-and-publish

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  build_client:
    runs-on: ubuntu-latest
    name: Build Client
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Get tag and short commit hash
      id: tag_hash
      run: |
        latest_tag=$(git describe --abbrev=0 --tags)
        short_hash=$(git rev-parse --short HEAD)
        echo "TAG_VERSION=${latest_tag}-${short_hash}" >> $GITHUB_ENV

    - name: Export game
      id: export
      uses: firebelley/godot-export@v4.7.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: ./
        use_godot_4: true
        verbose: true
        export_debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Enable threads for Chrome
      run: |
        curl https://raw.githubusercontent.com/josephrocca/clip-image-sorter/main/enable-threads.js > ${{ steps.export.outputs.build_directory }}/Web/enable-threads.js

    - uses: actions/upload-artifact@v3
      with:
        name: youtd-${{ env.TAG_VERSION }}
        path: ${{ steps.export.outputs.build_directory }}/Web/*

    outputs:
      tag_version: ${{ env.TAG_VERSION }}

  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: build_client
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: youtd-${{ needs.build_client.outputs.tag_version }}
        
    - name: Release client
      uses: ncipollo/release-action@v1.11.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ needs.build_client.outputs.tag_version }} # Note that the 'v' in front was necessary to get this action attach artifacts to the tag
        artifacts: ./*
        
    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
